
const randomString = (length) => [ ...Array(length) ].map(() => (~~(Math.random() * 36)).toString(36)).join('')

describe("Kreira i šalje jednu ispunjenu Contact us formu, ali sa jako puno znakova u poruci",()=>{

    it("Otvara stranicu za kontakt",()=>{
        
        cy.visit("http://automationpractice.com/index.php");
        cy.url().should("contain","automationpractice.com");
        cy.xpath("//div[@id='contact-link']").click();
        cy.url().should("contain","controller=contact");
    })

    it("Ispunjava i šalje formu",()=>{

        cy.xpath("//select[@id='id_contact']").select(2);
        cy.xpath("//input[@id='email']").click().type("pikachu@gmail.com");
        cy.xpath("//input[@id='id_order']").click().type("456");
        cy.xpath("//textarea[@id='message']").click().type(randomString(500000));
        cy.xpath("//button[@id='submitMessage']").click();
        //Opet isti problem mora se dva puta stisnuti submit
        cy.xpath("//button[@id='submitMessage']").click();
        cy.xpath("//p[@class='alert alert-success']").should("exist");
    })
}) 



























//var poruka = "asijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuoasijsimocajofimejfejesiomjfiisohsgodrgousnrdogcnsrdogcndfcgocndofgnodngcdofngcoerngreuo"